In [2]:
import numpy as np
x = np.array([2,3,4])
print(x)
type(x)

[2 3 4]


numpy.ndarray

In [7]:
y = np.array([[2,3,4],[3,5,6]])
print(y)

[[2 3 4]
 [3 5 6]]


In [14]:
z = np.array([[[1],[2]],[[4],[7]]])
print(z)
print(z.ndim)
print(z.shape)
print(z.size)

[[[1]
  [2]]

 [[4]
  [7]]]
3
(2, 2, 1)
4


In [18]:
x = np.arange(2,10)
print(x)
##default is +1
x = np.arange(2,10,3)
print(x)
#arange does not take last value

[2 3 4 5 6 7 8 9]
[2 5 8]


In [19]:
x = np.linspace(1, 10, 5)
print(x)
# linspace takes last value

[ 1.    3.25  5.5   7.75 10.  ]


In [23]:
# zeros gives you arrays with all-zeros
x = np.zeros(5)
print(x)

x = np.zeros((2,3))
print(x)

# ones gives you arrays with all-ones
x = np.ones((2,3,4))
print(x)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [24]:
# identity matrix
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# elementary row operations on identity matrix
x = np.diag(np.array([1,2,3,4]))
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [29]:
# random numbers between 0 and 1
x = np.random.random(4)
print(x)

x = np.random.random((3,5))
print(x)

# standard normal distribution
x = np.random.randn(4)
print(x)

[0.12309077 0.61444493 0.99267216 0.17894714]
[-1.07910474 -0.59762774 -0.36782775  0.45900174]
[[0.26225499 0.28553835 0.98465464 0.49954491 0.06357158]
 [0.21864959 0.21963405 0.12524848 0.1456061  0.81800427]
 [0.18716609 0.0985014  0.52200957 0.80168908 0.784662  ]]


In [31]:
#random numbers in given range, note that last number is not in range
x = np.random.randint(2,10,5)
print(x)

x = np.random.randint(2,10,(2,3))
print(x)

[3 5 5 6 9]
[[9 4 4]
 [3 3 6]]


In [35]:
x = np.random.randint(1,200,10)
print(x)


[ 36  38  87  22  14  61 184 117 179 156]
22


In [43]:
# get 3rd index
print(x[3])

print(x[2:5])
print(x[[2,5]])
print(x[-3])
print(x[-4:-2])
print(x[1:7:2])
# reverse the vector
print(x[::-1])

22
[87 22 14]
[87 61]
117
[184 117]
[38 22 61]
[156 179 117 184  61  14  22  87  38  36]


In [44]:
x = np.random.randint(1, 100, (4,5))
print(x)

[[18 37 52 87  4]
 [54 40 11 63 29]
 [43 39 33 22 84]
 [52 67 13 84 90]]


In [49]:
# get 2nd row and 3rd column value
print(x[2,3])

# get 2nd row values
print(x[2, :])

# get 1st column- 1 is the index!
print(x[:, 1])

22
[43 39 33 22 84]
[37 40 39 67]


In [50]:
x = np.random.randint(1, 10, 5)
print(x)

[8 4 2 8 6]


In [53]:
# mathematical operations on arrays
print (x + 3)
print(x * 3)
print (x ** 2)

# logical operations
print(x > 3)


[11  7  5 11  9]
[24 12  6 24 18]
[64 16  4 64 36]
[ True  True False  True  True]


In [54]:
ix = np.array([True, False, True, False, True])
print(ix)

[ True False  True False  True]


In [55]:
# take true values from a matrix
print(x[ix])

[8 2 6]


In [3]:
x = np.array([20, 30, 40, -10, 20])
print(x)

[ 20  30  40 -10  20]


In [6]:
ix = x > 0
print(ix)
# take true values from matrix
print(x[ix])
print(x[x > 0])

[ True  True  True False  True]
[20 30 40 20]
[20 30 40 20]
